config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:new, :create]
  
  resources :votes, only: [:create]
  
  resources :rankings, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_one :vote
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  
  validates :user_id, presence: true
  validates :category, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  def index
    #@votes = Vote.find(Vote.group(:category).order('count(category) desc').pluck(:id))
    @rankings = Vote.group(:category).order('count_category DESC').count(:category)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインしました'
      redirect_to '#'
    else
      flash.now[:danger] = 'ログインできませんでした'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_path
  end
  
  private
  
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @vote = Vote.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました' 
      redirect_to login_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    @user = current_user
    @vote = current_user.build_vote(category: params[:category])
    if @vote.save
      flash[:success] = '投票しました'
      redirect_to root_url
    else 
      flash.now[:danger] = '投票できませんでした'
      render 'toppages/index'
    end
  end
  
  private
  
  def vote_params
    params.require(:vote).permit(:category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">i.demand</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to '結果発表', rankings_path %></li>
            <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Signup', signup_path %></li>
            <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>i.demand</title>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="conteiner">
      <%= render 'layouts/flash_messages' %>
      
    
    <%= yield %>
    </div>
  </body>
</html>

app/views/rankings/index.html.erb
<h1 class="text-center bg-primary"><strong>＊結果発表＊</strong></h1>
<br>
<br>

  <div class="row">
      <div class="col-md-3 col-md-offset-1 col-sm-6 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <h1 class="text-center">交通</h1>
            <h3 class="text-center">Traffic</h3>
            <h2 class="text-center"><%= @rankings["koutsu"] %>票</h2> 
          </div>
        </div>
      </div>
      <div class="col-md-3 col-md-offset-1 col-sm-6 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <h1 class="text-center">税金問題</h1>
            <h3 class="text-center">Tax</h3>
            <h2 class="text-center"><%= @rankings["zeikin"] %>票</h2>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-md-offset-1 col-sm-6 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <h1 class="text-center">環境問題</h1>
            <h3 class="text-center">Environment</h3>
            <h2 class="text-center"><%= @rankings["kankyo"] %>票</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
    
  <div class="row">  
      <div class="col-md-3 col-md-offset-1 col-sm-6 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <h1 class="text-center">年金</h1>
            <h3 class="text-center">Pension</h3>
            <h2 class="text-center"><%= @rankings["nenkin"] %>票</h2>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-md-offset-1 col-sm-6 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <h1 class="text-center">就労問題</h1>
            <h3 class="text-center">Jobs</h3>
            <h2 class="text-center"><%= @rankings["shigoto"] %>票</h2>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-md-offset-1 col-sm-6 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <h1 class="text-center">教育</h1>
            <h3 class="text-center">Education</h3>
            <h2 class="text-center"><%= @rankings["kyoiku"] %>票</h2>
          </div>
        </div>
      </div>
  </div>
  <br>
  <br>
  <div class="text-center">
  <%= link_to 'ログアウトする', logout_path, method: :delete, class: 'btn btn-lg btn-warning' %>
  </div>

app/views/rankings/show.html.erb
<h1>ランキング</h1>

  <div class="row">
    
      <div class="category">
        <div class="col-md-3 col-md-offset-1 col-sm-6 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-body">
      </div>
  </div>
  

app/views/toppages/index.html.erb
<% if logged_in? %>
  <% if current_user.vote %>
    <h1 class="text-center">投票済みです。</h1>
    <h3 class="text-center">結果発表ページへ移動して下さい。</h3>
    <br>
    <br>
    <div class="text-center">
    <%= link_to '結果発表ページへ', rankings_path, class: 'btn btn-warning btn-lg' %>
    </div>
  <% else %>
    <div class="row">
      <div class="col-md-3 col-md-offset-1 col-sm-6 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <h1 class="text-center">交通</h1>
            <h3 class="text-center">Traffic</h3>
            <%= form_for(@vote) do |f| %>
            <%= hidden_field_tag :category, 'koutsu' %>
            <%= f.submit '投票', class: 'btn btn-success btn-block' %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-md-offset-1 col-sm-6 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <h1 class="text-center">税金問題</h1>
            <h3 class="text-center">Tax</h3>
            <%= form_for(@vote) do |f| %>
            <%= hidden_field_tag :category, 'zeikin' %>
            <%= f.submit '投票', class: 'btn btn-success btn-block' %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-md-offset-1 col-sm-6 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <h1 class="text-center">環境問題</h1>
            <h3 class="text-center">Environment</h3>
            <%= form_for(@vote) do |f| %>
            <%= hidden_field_tag :category, 'kankyo' %>
            <%= f.submit '投票', class: 'btn btn-success btn-block' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
      <div class="col-md-3 col-md-offset-1 col-sm-6 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <h1 class="text-center">年金</h1>
            <h3 class="text-center">Pension</h3>
            <%= form_for(@vote) do |f| %>
            <%= hidden_field_tag :category, 'nenkin' %>
            <%= f.submit '投票', class: 'btn btn-success btn-block' %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-md-offset-1 col-sm-6 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <h1 class="text-center">就労問題</h1>
            <h3 class="text-center">Jobs</h3>
            <%= form_for(@vote) do |f| %>
            <%= hidden_field_tag :category, 'shigoto' %>
            <%= f.submit '投票', class: 'btn btn-success btn-block' %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-md-offset-1 col-sm-6 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <h1 class="text-center">教育</h1>
            <h3 class="text-center">Education</h3>
            <%= form_for(@vote) do |f| %>
            <%= hidden_field_tag :category, 'kyoiku' %>
            <%= f.submit '投票', class: 'btn btn-success btn-block' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <div class="col-md-6 col-md-offset-5 col-sm-6 col-xs-11"> 
  <%= link_to '結果発表ページへ', rankings_path, class: 'btn btn-lg btn-warning' %>
  </div>
  <% end %>
<% else %>
<div class="center jumbotron">
  <div class="text-center">
    <h1>i.demand</h1>
  <br>
  <p class="text-primary">この中で、何が１番気になる？今、興味のあることに投票しよう！</p><br>
  <p class="text-primary">あなたの一票で何かが変わるかも？</p>
  <p class="text-danger">投票ボタンを押した後は、再投票ができないので、<br>
                         押し間違えには気をつけて下さい。</p>
  <br>
  <%= link_to 'Sign up', signup_path, class: 'btn btn-lg btn-success' %>
  </div>
</div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
    
      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <%= f.submit 'Sign up', class: 'btn btn-warning btn-block' %>
    <% end %>
  </div>
</div>

app/views/votes/create.html.erb
<div class="row">
  <div class="item">
    <div class="col-md-3 col-sm-4 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <p>交通</p>
          <br>
          <br>
          <div class="投票" btn btn-success btn-xs></div>
        </div>
      </div>
    </div>
  </div>
</div>